# Generated by Django 5.0.4 on 2024-04-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avator",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
