[tool.poetry]
name = "airbnb-backend"
version = "0.1.0"
description = ""
authors = ["seungjinhan <hanblues@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.4"
beautifulsoup4 = "^4.12.3"
pillow = "^10.3.0"
djangorestframework = "^3.15.1"
strawberry-graphql = {extras = ["debug-server"], version = "^0.227.2"}
strawberry-graphql-django = "^0.39.1"
pyjwt = "^2.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
